- name: usability
  color: "1abc9c"
  description: "Usability / UX"
- name: heuristic
  color: "9b59b6"
  description: "Heuristic evaluation"
- name: "severity:1"
  color: "e0f7fa"
  description: "Minor"
- name: "severity:2"
  color: "b2ebf2"
  description: "Low"
- name: "severity:3"
  color: "80deea"
  description: "Medium"
- name: "severity:4"
  color: "4dd0e1"
  description: "High"
- name: "severity:5"
  color: "26c6da"
  description: "Critical"

# Heuristic buckets as labels (valkvætt)
- name: "Visibility & Feedback"
  color: "34495e"
- name: "Match to real world"
  color: "2c3e50"
- name: "User control & error prevention"
  color: "7f8c8d"
- name: "Consistency & standards"
  color: "95a5a6"
- name: "Recognition over recall"
  color: "bdc3c7"
- name: "Flexibility & efficiency"
  color: "16a085"
- name: "Aesthetics & minimalism"
  color: "27ae60"
